version: '3.8'

services:

  # Prefect Database
  database:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prefect
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data

  # Prefect Server API and UI
  server:
    image: crime-trends:v001
    container_name: my-crime-trends-server
    restart: always
    volumes:
      - prefect:/root/.prefect
    entrypoint: ["prefect", "orion", "start", "--host", "0.0.0.0", "--port", "4200"]
    environment:
      # If you want to access Prefect Server from anywhere other than the Docker host machine, you will need to change
      # PREFECT_UI_URL to match the external hostname/IP used to load the  UI in your web browser.
      - PREFECT_ORION_API_HOST=0.0.0.0
      - PREFECT_ORION_API_PORT=4200
      - PREFECT_ORION_UI_API_URL=http://127.0.0.1:4200/api
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@database:5432/prefect
    ports:
      - 4200:4200
    depends_on:
      - database

  # Prefect Agent
  agent:
    image: crime-trends:v001
    container_name: my-crime-trends-agent
    restart: always
    entrypoint: ["prefect", "agent", "start", "-q", "default"]
    volumes:
      - "./flows:/app/flows"
    environment:
      - PREFECT_API_URL=http://server:4200/api
#       Use PREFECT_API_KEY if connecting the agent to Prefect Cloud
#     - PREFECT_API_KEY=YOUR_API_KEY

  # pipeline
  my-crime-trends-container:
    image: crime-trends:v001
    container_name: my-crime-trends-container
    volumes:
      - "./flows:/app/flows"
      - "./dbt_crime:/app/dbt_crime"
#      - "${KEY_FILE_PATH}:/app/${KEY_FILE}"
#      - "$HOME/.gc/crime-trends-explorer-user-key.json:/app/crime-trends-explorer-user-key.json"
    environment:
      - PREFECT_API_URL=http://server:4200/api
#      - GOOGLE_APPLICATION_CREDENTIALS=/app/${KEY_FILE}
#      - GOOGLE_APPLICATION_CREDENTIALS=/app/crime-trends-explorer-user-key.json
    tty: true
    stdin_open: true

volumes:
  prefect:
  db:
networks:
  default:
    name: prefect-network