version: 2

macros:
  - name: get_priority_description
    description: >
      This macro receives a priority and returns the corresponding description.
    arguments:
      - name: priority
        type: int
        description: > 
          priority value.
          Must be one of the accepted values, otherwise the macro will return null